name: CI/CD with Docker

on:
  push:
    branches:
      - main
      - develop

env:
  DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}-${{ github.sha }}
          labels: ${{ github.ref_name }}

  deploy-to-dev:
    needs: build-and-push
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Development Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          username: ${{ secrets.DEV_SSH_USERNAME }}
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          script: |
            sudo docker pull ${{ env.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}-${{ github.sha }}
            
            sudo docker stop ${{ github.event.repository.name }}-dev || true
            sudo docker rm ${{ github.event.repository.name }}-dev || true
            
            sudo docker run -d --name ${{ github.event.repository.name }}-dev -p 8080:8080 ${{ env.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}-${{ github.sha }}
